name 'chefandanalytics'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chefservers'
long_description 'Installs/Configures chefservers'
version '0.1.0'
